#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

# nice coloured prompt
export PS1='\[\e]0;\u@\h: \w\a\]\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# mac2bat converts raw MACs to bat-names in piped output (i.e. "iwinfo scan | mac2bat"). bat2mac does the reverse.
alias mac2bat='sed "$(sed -nr "{s/.*(..:..:..:..:..:..)[[:space:]]+([^[:space:]]+).*/s|\1|\2|Ig;/p}" /etc/bat-hosts)"'
alias bat2mac='sed "$(sed -nr "{s/.*(..:..:..:..:..:..)[[:space:]]+([^[:space:]]+).*/s|\2|\1|Ig;/p}" /etc/bat-hosts)"'

# nice coloured prompt
export PS1='\[\e]0;\u@\h: \w\a\]\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# mac2bat converts raw MACs to bat-names in piped output (i.e. "iwinfo scan | mac2bat"). bat2mac does the reverse.
alias mac2bat='sed "$(sed -nr "{s/.*(..:..:..:..:..:..)[[:space:]]+([^[:space:]]+).*/s|\1|\2|Ig;/p}" /etc/bat-hosts)"'
alias bat2mac='sed "$(sed -nr "{s/.*(..:..:..:..:..:..)[[:space:]]+([^[:space:]]+).*/s|\2|\1|Ig;/p}" /etc/bat-hosts)"'
